### ISSUE TITLE
Where's WilmAPI?

### ISSUE THREAD

**Issue by developerfromjokela** [PaulusParssinen/Wilma.Desktop#1]
There's this dependency called WilmAPI. Where can I get that?

**Comment by PaulusParssinen** [comment]
'WilmAPI' is now called [Wilma.Api](https://github.com/PaulusParssinen/Wilma.Api) but its missing most of its functionality due to refactoring. I haven't touched either of these projects for a long time but I think I can bring them up to date in just a couple of days. 

I'll keep this issue open until I resolve this missing dependency problem.

**Comment by developerfromjokela** [comment]
Ok
